# -*- coding: utf-8 -*-

# Copyright 2004-2007 Nanorex, Inc.  See LICENSE file for details.
# Form implementation generated from reading ui file 'ElementSelectorDialog.ui'
#
# Created: Wed Sep 20 10:12:41 2006
#      by: PyQt4 UI code generator 4.0.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ElementSelectorDialog(object):
    def setupUi(self, ElementSelectorDialog):
        ElementSelectorDialog.setObjectName("ElementSelectorDialog")
        ElementSelectorDialog.resize(QtCore.QSize(QtCore.QRect(0,0,214,426).size()).expandedTo(ElementSelectorDialog.minimumSizeHint()))
        ElementSelectorDialog.setMinimumSize(QtCore.QSize(200,150))

        palette = QtGui.QPalette()
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(0),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(1),QtGui.QColor(230,231,230))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(2),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(3),QtGui.QColor(242,243,242))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(4),QtGui.QColor(115,115,115))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(5),QtGui.QColor(153,154,153))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(6),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(7),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(8),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(9),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(10),QtGui.QColor(230,231,230))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(11),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(12),QtGui.QColor(0,0,128))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(13),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(14),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(15),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(16),QtGui.QColor(232,232,232))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(0),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(1),QtGui.QColor(230,231,230))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(2),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(3),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(4),QtGui.QColor(115,115,115))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(5),QtGui.QColor(153,154,153))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(6),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(7),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(8),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(9),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(10),QtGui.QColor(230,231,230))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(11),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(12),QtGui.QColor(0,0,128))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(13),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(14),QtGui.QColor(0,0,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(15),QtGui.QColor(255,0,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(16),QtGui.QColor(232,232,232))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(0),QtGui.QColor(128,128,128))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(1),QtGui.QColor(230,231,230))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(2),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(3),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(4),QtGui.QColor(115,115,115))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(5),QtGui.QColor(153,154,153))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(6),QtGui.QColor(128,128,128))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(7),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(8),QtGui.QColor(128,128,128))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(9),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(10),QtGui.QColor(230,231,230))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(11),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(12),QtGui.QColor(0,0,128))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(13),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(14),QtGui.QColor(0,0,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(15),QtGui.QColor(255,0,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(16),QtGui.QColor(232,232,232))
        ElementSelectorDialog.setPalette(palette)

        self.vboxlayout = QtWidgets.QVBoxLayout(ElementSelectorDialog)
        self.vboxlayout.setContentsMargins(2, 2, 2, 2)
        self.vboxlayout.setSpacing(2)
        self.vboxlayout.setObjectName("vboxlayout")

        self.elementFrame = QtWidgets.QFrame(ElementSelectorDialog)
        self.elementFrame.setMinimumSize(QtCore.QSize(200,150))
        self.elementFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.elementFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.elementFrame.setObjectName("elementFrame")
        self.vboxlayout.addWidget(self.elementFrame)

        self.elementButtonGroup = QtWidgets.QGroupBox(ElementSelectorDialog)
        self.elementButtonGroup.setMinimumSize(QtCore.QSize(0,126))
        self.elementButtonGroup.setObjectName("elementButtonGroup")

        self.gridlayout = QtWidgets.QGridLayout(self.elementButtonGroup)
        self.gridlayout.setContentsMargins(2, 2, 2, 2)
        self.gridlayout.setSpacing(0)
        self.gridlayout.setObjectName("gridlayout")

        self.toolButton1 = QtWidgets.QToolButton(self.elementButtonGroup)
        self.toolButton1.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton1.setCheckable(True)
        self.toolButton1.setObjectName("toolButton1")
        self.gridlayout.addWidget(self.toolButton1,0,4,1,1)

        self.toolButton2 = QtWidgets.QToolButton(self.elementButtonGroup)
        self.toolButton2.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton2.setCheckable(True)
        self.toolButton2.setObjectName("toolButton2")
        self.gridlayout.addWidget(self.toolButton2,0,5,1,1)

        self.toolButton6 = QtWidgets.QToolButton(self.elementButtonGroup)
        self.toolButton6.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton6.setCheckable(True)
        self.toolButton6.setObjectName("toolButton6")
        self.gridlayout.addWidget(self.toolButton6,1,1,1,1)

        self.toolButton7 = QtWidgets.QToolButton(self.elementButtonGroup)
        self.toolButton7.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton7.setCheckable(True)
        self.toolButton7.setObjectName("toolButton7")
        self.gridlayout.addWidget(self.toolButton7,1,2,1,1)

        self.toolButton8 = QtWidgets.QToolButton(self.elementButtonGroup)
        self.toolButton8.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton8.setCheckable(True)
        self.toolButton8.setObjectName("toolButton8")
        self.gridlayout.addWidget(self.toolButton8,1,3,1,1)

        self.toolButton10 = QtWidgets.QToolButton(self.elementButtonGroup)
        self.toolButton10.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton10.setCheckable(True)
        self.toolButton10.setObjectName("toolButton10")
        self.gridlayout.addWidget(self.toolButton10,1,5,1,1)

        self.toolButton9 = QtWidgets.QToolButton(self.elementButtonGroup)
        self.toolButton9.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton9.setCheckable(True)
        self.toolButton9.setObjectName("toolButton9")
        self.gridlayout.addWidget(self.toolButton9,1,4,1,1)

        self.toolButton13 = QtWidgets.QToolButton(self.elementButtonGroup)
        self.toolButton13.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton13.setCheckable(True)
        self.toolButton13.setObjectName("toolButton13")
        self.gridlayout.addWidget(self.toolButton13,2,0,1,1)

        self.toolButton17 = QtWidgets.QToolButton(self.elementButtonGroup)
        self.toolButton17.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton17.setCheckable(True)
        self.toolButton17.setObjectName("toolButton17")
        self.gridlayout.addWidget(self.toolButton17,2,4,1,1)

        self.toolButton5 = QtWidgets.QToolButton(self.elementButtonGroup)
        self.toolButton5.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton5.setCheckable(True)
        self.toolButton5.setObjectName("toolButton5")
        self.gridlayout.addWidget(self.toolButton5,1,0,1,1)

        self.toolButton10_2 = QtWidgets.QToolButton(self.elementButtonGroup)
        self.toolButton10_2.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton10_2.setCheckable(True)
        self.toolButton10_2.setObjectName("toolButton10_2")
        self.gridlayout.addWidget(self.toolButton10_2,2,5,1,1)

        self.toolButton15 = QtWidgets.QToolButton(self.elementButtonGroup)
        self.toolButton15.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton15.setCheckable(True)
        self.toolButton15.setObjectName("toolButton15")
        self.gridlayout.addWidget(self.toolButton15,2,2,1,1)

        self.toolButton16 = QtWidgets.QToolButton(self.elementButtonGroup)
        self.toolButton16.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton16.setCheckable(True)
        self.toolButton16.setObjectName("toolButton16")
        self.gridlayout.addWidget(self.toolButton16,2,3,1,1)

        self.toolButton14 = QtWidgets.QToolButton(self.elementButtonGroup)
        self.toolButton14.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton14.setCheckable(True)
        self.toolButton14.setObjectName("toolButton14")
        self.gridlayout.addWidget(self.toolButton14,2,1,1,1)

        self.toolButton33 = QtWidgets.QToolButton(self.elementButtonGroup)
        self.toolButton33.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton33.setCheckable(True)
        self.toolButton33.setObjectName("toolButton33")
        self.gridlayout.addWidget(self.toolButton33,3,2,1,1)

        self.toolButton34 = QtWidgets.QToolButton(self.elementButtonGroup)
        self.toolButton34.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton34.setCheckable(True)
        self.toolButton34.setObjectName("toolButton34")
        self.gridlayout.addWidget(self.toolButton34,3,3,1,1)

        self.toolButton35 = QtWidgets.QToolButton(self.elementButtonGroup)
        self.toolButton35.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton35.setCheckable(True)
        self.toolButton35.setObjectName("toolButton35")
        self.gridlayout.addWidget(self.toolButton35,3,4,1,1)

        self.toolButton36 = QtWidgets.QToolButton(self.elementButtonGroup)
        self.toolButton36.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton36.setCheckable(True)
        self.toolButton36.setObjectName("toolButton36")
        self.gridlayout.addWidget(self.toolButton36,3,5,1,1)

        self.toolButton32 = QtWidgets.QToolButton(self.elementButtonGroup)
        self.toolButton32.setMinimumSize(QtCore.QSize(30,30))
        self.toolButton32.setCheckable(True)
        self.toolButton32.setObjectName("toolButton32")
        self.gridlayout.addWidget(self.toolButton32,3,1,1,1)
        self.vboxlayout.addWidget(self.elementButtonGroup)

        spacerItem = QtWidgets.QSpacerItem(20,16,QtWidgets.QSizePolicy.Minimum,QtWidgets.QSizePolicy.Fixed)
        self.vboxlayout.addItem(spacerItem)

        self.vboxlayout1 = QtWidgets.QVBoxLayout()
        self.vboxlayout1.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setObjectName("vboxlayout1")

        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")

        self.TransmuteButton = QtWidgets.QPushButton(ElementSelectorDialog)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy(1),QtWidgets.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TransmuteButton.sizePolicy().hasHeightForWidth())
        self.TransmuteButton.setSizePolicy(sizePolicy)
        self.TransmuteButton.setObjectName("TransmuteButton")
        self.hboxlayout.addWidget(self.TransmuteButton)

        spacerItem1 = QtWidgets.QSpacerItem(16,20,QtWidgets.QSizePolicy.Expanding,QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.vboxlayout1.addLayout(self.hboxlayout)

        self.transmuteCheckBox = QtWidgets.QCheckBox(ElementSelectorDialog)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy(1),QtWidgets.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transmuteCheckBox.sizePolicy().hasHeightForWidth())
        self.transmuteCheckBox.setSizePolicy(sizePolicy)
        self.transmuteCheckBox.setObjectName("transmuteCheckBox")
        self.vboxlayout1.addWidget(self.transmuteCheckBox)
        self.vboxlayout.addLayout(self.vboxlayout1)

        spacerItem2 = QtWidgets.QSpacerItem(20,40,QtWidgets.QSizePolicy.Minimum,QtWidgets.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem2)

        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setObjectName("hboxlayout1")

        spacerItem3 = QtWidgets.QSpacerItem(106,20,QtWidgets.QSizePolicy.Expanding,QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem3)

        self.closePTableButton = QtWidgets.QPushButton(ElementSelectorDialog)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy(1),QtWidgets.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closePTableButton.sizePolicy().hasHeightForWidth())
        self.closePTableButton.setSizePolicy(sizePolicy)
        self.closePTableButton.setDefault(True)
        self.closePTableButton.setObjectName("closePTableButton")
        self.hboxlayout1.addWidget(self.closePTableButton)

        spacerItem4 = QtWidgets.QSpacerItem(10,20,QtWidgets.QSizePolicy.Fixed,QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem4)
        self.vboxlayout.addLayout(self.hboxlayout1)

        spacerItem5 = QtWidgets.QSpacerItem(20,16,QtWidgets.QSizePolicy.Minimum,QtWidgets.QSizePolicy.Fixed)
        self.vboxlayout.addItem(spacerItem5)

        self.retranslateUi(ElementSelectorDialog)
        self.closePTableButton.clicked.connect(ElementSelectorDialog.close)
        QtCore.QMetaObject.connectSlotsByName(ElementSelectorDialog)
        ElementSelectorDialog.setTabOrder(self.TransmuteButton,self.transmuteCheckBox)
        ElementSelectorDialog.setTabOrder(self.transmuteCheckBox,self.closePTableButton)

    def retranslateUi(self, ElementSelectorDialog):
        ElementSelectorDialog.setWindowTitle(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Element Selector", None))
        self.elementFrame.setToolTip(QtCore.QCoreApplication.translate("ElementSelectorDialog", "3D thumbnail view", None))
        self.toolButton1.setToolTip(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Hydrogen", None))
        self.toolButton1.setText(QtCore.QCoreApplication.translate("ElementSelectorDialog", "H", None))
        self.toolButton1.setShortcut(QtCore.QCoreApplication.translate("ElementSelectorDialog", "H", None))
        self.toolButton2.setToolTip(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Helium", None))
        self.toolButton2.setText(QtCore.QCoreApplication.translate("ElementSelectorDialog", "He", None))
        self.toolButton6.setToolTip(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Carbon", None))
        self.toolButton6.setText(QtCore.QCoreApplication.translate("ElementSelectorDialog", "C", None))
        self.toolButton6.setShortcut(QtCore.QCoreApplication.translate("ElementSelectorDialog", "C", None))
        self.toolButton7.setToolTip(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Nitrogen", None))
        self.toolButton7.setText(QtCore.QCoreApplication.translate("ElementSelectorDialog", "N", None))
        self.toolButton7.setShortcut(QtCore.QCoreApplication.translate("ElementSelectorDialog", "N", None))
        self.toolButton8.setToolTip(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Oxygen", None))
        self.toolButton8.setText(QtCore.QCoreApplication.translate("ElementSelectorDialog", "O", None))
        self.toolButton8.setShortcut(QtCore.QCoreApplication.translate("ElementSelectorDialog", "O", None))
        self.toolButton10.setToolTip(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Neon", None))
        self.toolButton10.setText(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Ne", None))
        self.toolButton9.setToolTip(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Fluorine", None))
        self.toolButton9.setText(QtCore.QCoreApplication.translate("ElementSelectorDialog", "F", None))
        self.toolButton9.setShortcut(QtCore.QCoreApplication.translate("ElementSelectorDialog", "F", None))
        self.toolButton13.setToolTip(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Aluminum", None))
        self.toolButton13.setText(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Al", None))
        self.toolButton17.setToolTip(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Chlorine", None))
        self.toolButton17.setText(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Cl", None))
        self.toolButton5.setToolTip(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Boron", None))
        self.toolButton5.setText(QtCore.QCoreApplication.translate("ElementSelectorDialog", "B", None))
        self.toolButton5.setShortcut(QtCore.QCoreApplication.translate("ElementSelectorDialog", "B", None))
        self.toolButton10_2.setToolTip(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Argon", None))
        self.toolButton10_2.setText(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Ar", None))
        self.toolButton15.setToolTip(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Phosphorus", None))
        self.toolButton15.setText(QtCore.QCoreApplication.translate("ElementSelectorDialog", "P", None))
        self.toolButton15.setShortcut(QtCore.QCoreApplication.translate("ElementSelectorDialog", "P", None))
        self.toolButton16.setToolTip(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Sulfur", None))
        self.toolButton16.setText(QtCore.QCoreApplication.translate("ElementSelectorDialog", "S", None))
        self.toolButton16.setShortcut(QtCore.QCoreApplication.translate("ElementSelectorDialog", "S", None))
        self.toolButton14.setToolTip(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Silicon", None))
        self.toolButton14.setText(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Si", None))
        self.toolButton33.setToolTip(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Arsenic", None))
        self.toolButton33.setText(QtCore.QCoreApplication.translate("ElementSelectorDialog", "As", None))
        self.toolButton34.setToolTip(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Selenium", None))
        self.toolButton34.setText(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Se", None))
        self.toolButton35.setToolTip(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Bromine", None))
        self.toolButton35.setText(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Br", None))
        self.toolButton36.setToolTip(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Krypton", None))
        self.toolButton36.setText(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Kr", None))
        self.toolButton32.setToolTip(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Germanium", None))
        self.toolButton32.setText(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Ge", None))
        self.TransmuteButton.setToolTip(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Transmute Selected Atoms", None))
        self.TransmuteButton.setText(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Transmute", None))
        self.transmuteCheckBox.setToolTip(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Check if transmuted atoms should keep all existing bonds,  even if chemistry is wrong", None))
        self.transmuteCheckBox.setText(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Force to Keep Bonds", None))
        self.closePTableButton.setText(QtCore.QCoreApplication.translate("ElementSelectorDialog", "Close", None))
